<?php
/**
 * Created by PhpStorm.
 * User: POE9
 * Date: 05/11/2019
 * Time: 10:06
 */
namespace Drupal\hello\Plugin\Block;

use Drupal\Core\Block\BlockBase;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;

/**
 *  Provides a session block
 *  @Block(
 *   id = "hello_session_block",
 *   admin_label = @Translation("Session actives")
 * )
 */

class SessionBlock extends BlockBase{


    protected function blockAccess(AccountInterface $account)
    {
        //return parent::blockAccess($account); // TODO: Change the autogenerated stub
        return AccessResult::allowedIfHasPermission($account, 'access hello');
    }

    /**
     * Implements Drupal\Core\Block\BlockBase::build().
     */
    public function build(){

        $database = \Drupal::database();
        $session = $database->select('sessions', 's')
                            ->countQuery()
                            ->execute();

        $session_total = $session->fetchField();

        return [
            '#markup' => $this->t('Nb session : %session.', [
                '%session' => $session_total,

            ]),
            '#cache' => [
                'keys' => ['hello_session_block'],
                'max-age' => '3',
            ],
        ];
    }
}