<?php

function email_form_mail($key, &$message, $params) {
    switch ($key){
        case 'node_mail':
            $message['from'] = 'no-reply@gmail.com';
            $message['subject'] = t('Node update');
            $message['body'][] = check_markup(t('Example test'));
            break;

    }
}

function email_form_node_update(\Drupal\Core\Entity\EntityInterface $entity){

    $mailManager = \Drupal::service('plugin.manager.mail');
    $mailManager->mail('email_form', 'node_mail', 'vangneva.ku@gmail.com', 'en', [], NULL, TRUE);
    drupal_set_message('Envoi email OK');

}