<?php
/**
 * déclare un hook mail
 * @param $key
 * @param $message
 * @param $params
 */
function email_form_mail($key, &$message, $params) {
    switch ($key){
        case 'node_mail':
            $message['from'] = 'no-reply@gmail.com';
            $message['subject'] = t('Node update');
            $message['body'][] = check_markup(t('Example test'));
            break;

    }
}

/**
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function email_form_node_update(\Drupal\Core\Entity\EntityInterface $entity){

    $emails = \Drupal::database()->select('email_form_node_subscriber', 'efns')
        ->fields('efns', ['email'])
        ->condition('nid', $entity->id())
        ->execute();

    $mailManager = \Drupal::service('plugin.manager.mail');
    foreach ($emails as $email){
        //$email->email;
        $mailManager->mail('email_form', 'node_mail', $email->email, 'en', [], NULL, TRUE);
        drupal_set_message('Envoi email OK for '. $email->email);
    }


}